apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  ports:
  - port: 8081
    targetPort: 8080
  selector:
    app: products
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 4
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: mzegarra/box-accounts:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080