apiVersion: v1
kind: Service
metadata:
  name: box-products
spec:
  ports:
  - port: 8081
    targetPort: 8080
  selector:
    app: box-products
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-products
spec:
  selector:
    matchLabels:
      app: box-products
  replicas: 4
  template:
    metadata:
      labels:
        app: box-products
    spec:
      containers:
        - name: box-products
          image: mzegarra/box-accounts:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080